### ISSUE TITLE
Rotate V2 sometimes not resolved in cycle

### ISSUE THREAD

**Issue by lavas1997** [gbiz123/tiktok-captcha-solver#18]
From time to time solving TikTok captcha on async Playwright solver starts cycling on seem to be incorrect solutions, since every next attempt returns same angle and solution for same outer and inner pictures, indicating that for some reason captcha remained the same and did not refresh or disappeared after solution expected to be successful. Here i'm providing several logs sets from captcha solver:

`

2025-04-14 11:05:19 DEBUG [root] page is tiktok
2025-04-14 11:05:19 DEBUG [root] v1 or v2 tiktok selector present 
2025-04-14 11:05:19 DEBUG [root] page is tiktok
2025-04-14 11:05:19 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide 
2025-04-14 11:05:19 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image 
2025-04-14 11:05:20 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img] 
2025-04-14 11:05:20 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute 
2025-04-14 11:05:20 DEBUG [root] detected rotate v2
2025-04-14 11:05:20 DEBUG [root] Detected rotate v2
2025-04-14 11:05:20 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute 
2025-04-14 11:05:20 DEBUG [root] fetching blob: https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate 
2025-04-14 11:05:20 DEBUG [root] fetching blob: https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate 
2025-04-14 11:05:21 DEBUG [root] Got API response
2025-04-14 11:05:21 DEBUG [root] Solution angle: angle=360 
2025-04-14 11:05:21 DEBUG [root] Solution distance: 284 
2025-04-14 11:05:29 DEBUG [root] page is tiktok
2025-04-14 11:05:39 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:05:39 DEBUG [root] fetching blob:https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:05:39 DEBUG [root] fetching blob:https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:05:40 DEBUG [root] Got API response
2025-04-14 11:05:40 DEBUG [root] Solution angle: angle=360
2025-04-14 11:05:40 DEBUG [root] Solution distance: 284
2025-04-14 11:05:49 DEBUG [root] page is tiktok
2025-04-14 11:05:59 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:05:59 DEBUG [root] fetching blob: https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:05:59 DEBUG [root] fetching blob:https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:06:00 DEBUG [root] Got API response
2025-04-14 11:06:00 DEBUG [root] Solution angle: angle=360
2025-04-14 11:06:00 DEBUG [root] Solution distance: 284
2025-04-14 11:06:07 DEBUG [root] page is tiktok
2025-04-14 11:06:17 DEBUG [root] page is tiktok
2025-04-14 11:06:27 DEBUG [root] page is tiktok
2025-04-14 11:06:27 DEBUG [root] v1 or v2 tiktok selector present
2025-04-14 11:06:27 DEBUG [root] page is tiktok
2025-04-14 11:06:27 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide
2025-04-14 11:06:27 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image
2025-04-14 11:06:27 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img]
2025-04-14 11:06:27 DEBUG [root] Detected selector: .captcha-verify-container div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:06:27 DEBUG [root] detected rotate v2
2025-04-14 11:06:27 DEBUG [root] Detected rotate v2
2025-04-14 11:06:27 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:06:27 DEBUG [root] fetching blob:https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:06:27 DEBUG [root] fetching blob:https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:06:28 DEBUG [root] Got API response
2025-04-14 11:06:28 DEBUG [root] Solution angle: angle=360
2025-04-14 11:06:28 DEBUG [root] Solution distance: 284
2025-04-14 11:06:36 DEBUG [root] page is tiktok
2025-04-14 11:06:46 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
`

`

2025-04-14 11:06:46 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:06:46 DEBUG [root] fetching blob:https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:06:46 DEBUG [root] fetching blob: https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:06:47 DEBUG [root] Got API response
2025-04-14 11:06:47 DEBUG [root] Solution angle: angle=360
2025-04-14 11:06:47 DEBUG [root] Solution distance: 284
2025-04-14 11:06:55 DEBUG [root] page is tiktok
2025-04-14 11:07:05 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:07:05 DEBUG [root] fetching blob:https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:07:05 DEBUG [root] fetching blob: https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:07:06 DEBUG [root] Got API response
2025-04-14 11:07:06 DEBUG [root] Solution angle: angle=360
2025-04-14 11:07:06 DEBUG [root] Solution distance: 284
2025-04-14 11:07:14 DEBUG [root] page is tiktok
2025-04-14 11:07:24 DEBUG [root] page is tiktok
2025-04-14 11:07:34 DEBUG [root] page is tiktok
2025-04-14 11:07:34 DEBUG [root] v1 or v2 tiktok selector present
2025-04-14 11:07:34 DEBUG [root] page is tiktok
2025-04-14 11:07:34 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide
2025-04-14 11:07:34 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image
2025-04-14 11:07:34 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img]
2025-04-14 11:07:34 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:07:34 DEBUG [root] detected rotate v2
2025-04-14 11:07:34 DEBUG [root] Detected rotate v2
2025-04-14 11:07:34 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:07:34 DEBUG [root] fetching blob: https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:07:34 DEBUG [root] fetching blob:https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:07:35 DEBUG [root] Got API response
2025-04-14 11:07:35 DEBUG [root] Solution angle: angle=360
2025-04-14 11:07:35 DEBUG [root] Solution distance: 284
2025-04-14 11:07:43 DEBUG [root] page is tiktok
2025-04-14 11:07:53 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:07:53 DEBUG [root] fetching blob: https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:07:53 DEBUG [root] fetching blob: https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:07:54 DEBUG [root] Got API response
2025-04-14 11:07:54 DEBUG [root] Solution angle: angle=360
2025-04-14 11:07:54 DEBUG [root] Solution distance: 284
2025-04-14 11:08:02 DEBUG [root] page is tiktok
2025-04-14 11:08:12 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-14 11:08:12 DEBUG [root] fetching blob: https://www.tiktok.com/c91cc01a-151e-4566-8c10-85744a8850f1 with async playwright javascript evaluate
2025-04-14 11:08:12 DEBUG [root] fetching blob:https://www.tiktok.com/b617c212-832b-48c5-990c-e10784bbaaa9 with async playwright javascript evaluate
2025-04-14 11:08:13 DEBUG [root] Got API response
2025-04-14 11:08:13 DEBUG [root] Solution angle: angle=360
2025-04-14 11:08:13 DEBUG [root] Solution distance: 284
2025-04-14 11:08:21 DEBUG [root] page is tiktok
2025-04-14 11:08:31 DEBUG [root] page is tiktok
`

**Comment by lavas1997** [comment]
It's unclear for me if captcha solution was correct, but for some reason wasn't applied on front end side; or it was incorrect and it constantly attempts to retry solve same captcha.
Also, maybe it would be useful to utilize refresh button if same captcha continues to appear?

**Comment by gbiz123** [comment]
It looks like it's fetching the same URL each time. Will have to investigate

**Comment by gbiz123** [comment]
> It's unclear for me if captcha solution was correct, but for some reason wasn't applied on front end side; or it was incorrect and it constantly attempts to retry solve same captcha. Also, maybe it would be useful to utilize refresh button if same captcha continues to appear?

I implemented your suggestion to refresh the captcha on failure. Please check the latest version 0.7.5

**Comment by lavas1997** [comment]
Hi! Just had a chance to check it out, got error on async playwright solver, it's not called with `await`:

```
/usr/local/lib/python3.11/site-packages/tiktok_captcha_solver/asyncplaywrightsolver.py:218: RuntimeWarning: coroutine 
    'Page.click' was never awaited
self.page.click(selectors.RotateV2.REFRESH_BUTTON)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by gbiz123** [comment]
> Is it possible to return some values from `solve_captcha_if_present` to mark if captcha was present and passed, was present and failed or not found at all? It would be helpful to handle further situations related to TikTok fetching based on captcha pass success.

I'll update the `await` statement when I get back to my computer. 

As for the request to return a value from solve captcha if present, you can call make calls to `captcha_is_present` and `solve_rotate_v2` separately as a working solution. `solve_captcha_if_present` is just a convenience method that calls these methods.

 I will not plan to implement any changes to the method signature of `solve_captcha_if_present`, but you can put in a PR.

**Comment by lavas1997** [comment]
I copy-pasted library code, fixed `await` bug locally, but it still doesn't help:

```
2025-04-16 11:18:40 DEBUG [root] page is tiktok
2025-04-16T11:18:40.910606257Z 2025-04-16 11:18:40 DEBUG [root] v1 or v2 tiktok selector present
2025-04-16T11:18:40.910625840Z 2025-04-16 11:18:40 DEBUG [root] page is tiktok
2025-04-16T11:18:40.913353673Z 2025-04-16 11:18:40 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide
2025-04-16T11:18:40.915639090Z 2025-04-16 11:18:40 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image
2025-04-16T11:18:40.917778757Z 2025-04-16 11:18:40 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img]
2025-04-16T11:18:40.922465548Z 2025-04-16 11:18:40 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:18:40.922480132Z 2025-04-16 11:18:40 DEBUG [root] detected rotate v2
2025-04-16T11:18:40.922537298Z 2025-04-16 11:18:40 DEBUG [root] Detected rotate v2
2025-04-16T11:18:40.926778882Z 2025-04-16 11:18:40 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:18:40.930027132Z 2025-04-16 11:18:40 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:18:40.930659090Z 2025-04-16 11:18:40 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:18:41.645325174Z 2025-04-16 11:18:41 DEBUG [root] Got API response
2025-04-16T11:18:41.645984382Z 2025-04-16 11:18:41 DEBUG [root] Solution angle: angle=81
2025-04-16T11:18:41.694759632Z 2025-04-16 11:18:41 DEBUG [root] Solution distance: 63
2025-04-16T11:18:44.164141092Z 2025-04-16 11:18:44 DEBUG [root] page is tiktok
2025-04-16T11:18:49.218832386Z 2025-04-16 11:18:49 DEBUG [root] clicked refresh button
2025-04-16T11:18:52.227949387Z 2025-04-16 11:18:52 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:18:52.231449887Z 2025-04-16 11:18:52 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:18:52.232104512Z 2025-04-16 11:18:52 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:18:52.813258429Z 2025-04-16 11:18:52 DEBUG [root] Got API response
2025-04-16T11:18:52.813999721Z 2025-04-16 11:18:52 DEBUG [root] Solution angle: angle=81
2025-04-16T11:18:52.822652096Z 2025-04-16 11:18:52 DEBUG [root] Solution distance: 63
2025-04-16T11:18:55.795650139Z 2025-04-16 11:18:55 DEBUG [root] page is tiktok
2025-04-16T11:19:00.833509419Z 2025-04-16 11:19:00 DEBUG [root] clicked refresh button
2025-04-16T11:19:03.839478962Z 2025-04-16 11:19:03 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:19:03.842065837Z 2025-04-16 11:19:03 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:19:03.842537962Z 2025-04-16 11:19:03 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:19:04.447298420Z 2025-04-16 11:19:04 DEBUG [root] Got API response
2025-04-16T11:19:04.447572670Z 2025-04-16 11:19:04 DEBUG [root] Solution angle: angle=81
2025-04-16T11:19:04.457825670Z 2025-04-16 11:19:04 DEBUG [root] Solution distance: 63
2025-04-16T11:19:06.794518130Z 2025-04-16 11:19:06 DEBUG [root] page is tiktok
2025-04-16T11:19:11.831432549Z 2025-04-16 11:19:11 DEBUG [root] clicked refresh button
2025-04-16T11:19:14.837436800Z 2025-04-16 11:19:14 DEBUG [root] page is tiktok
2025-04-16T11:19:24.853887597Z 2025-04-16 11:19:24 DEBUG [root] page is tiktok
2025-04-16T11:19:24.861129888Z 2025-04-16 11:19:24 DEBUG [root] v1 or v2 tiktok selector present
2025-04-16T11:19:24.861169138Z 2025-04-16 11:19:24 DEBUG [root] page is tiktok
2025-04-16T11:19:24.864708597Z 2025-04-16 11:19:24 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide
2025-04-16T11:19:24.867704222Z 2025-04-16 11:19:24 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image
2025-04-16T11:19:24.871036847Z 2025-04-16 11:19:24 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img]
2025-04-16T11:19:24.877103805Z 2025-04-16 11:19:24 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:19:24.877143347Z 2025-04-16 11:19:24 DEBUG [root] detected rotate v2
2025-04-16T11:19:24.877145388Z 2025-04-16 11:19:24 DEBUG [root] Detected rotate v2
2025-04-16T11:19:24.883294472Z 2025-04-16 11:19:24 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:19:24.887050638Z 2025-04-16 11:19:24 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:19:24.887621763Z 2025-04-16 11:19:24 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:19:25.481845472Z 2025-04-16 11:19:25 DEBUG [root] Got API response
2025-04-16T11:19:25.482186055Z 2025-04-16 11:19:25 DEBUG [root] Solution angle: angle=81
2025-04-16T11:19:25.493262639Z 2025-04-16 11:19:25 DEBUG [root] Solution distance: 63
2025-04-16T11:19:27.874358459Z 2025-04-16 11:19:27 DEBUG [root] page is tiktok
2025-04-16T11:19:32.915830295Z 2025-04-16 11:19:32 DEBUG [root] clicked refresh button
2025-04-16T11:19:35.926947379Z 2025-04-16 11:19:35 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:19:35.931031963Z 2025-04-16 11:19:35 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:19:35.931729504Z 2025-04-16 11:19:35 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:19:36.512567796Z 2025-04-16 11:19:36 DEBUG [root] Got API response
2025-04-16T11:19:36.512839380Z 2025-04-16 11:19:36 DEBUG [root] Solution angle: angle=81
2025-04-16T11:19:36.522429005Z 2025-04-16 11:19:36 DEBUG [root] Solution distance: 63
2025-04-16T11:19:38.902345506Z 2025-04-16 11:19:38 DEBUG [root] page is tiktok
2025-04-16T11:19:43.947401716Z 2025-04-16 11:19:43 DEBUG [root] clicked refresh button
2025-04-16T11:19:46.962936218Z 2025-04-16 11:19:46 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:19:46.965948468Z 2025-04-16 11:19:46 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:19:46.966437385Z 2025-04-16 11:19:46 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:19:47.550335260Z 2025-04-16 11:19:47 DEBUG [root] Got API response
2025-04-16T11:19:47.550688843Z 2025-04-16 11:19:47 DEBUG [root] Solution angle: angle=81
2025-04-16T11:19:47.560469843Z 2025-04-16 11:19:47 DEBUG [root] Solution distance: 63
2025-04-16T11:19:50.244825886Z 2025-04-16 11:19:50 DEBUG [root] page is tiktok
2025-04-16T11:19:55.280584555Z 2025-04-16 11:19:55 DEBUG [root] clicked refresh button
2025-04-16T11:19:58.285191167Z 2025-04-16 11:19:58 DEBUG [root] page is tiktok
2025-04-16T11:20:08.295041089Z 2025-04-16 11:20:08 DEBUG [root] page is tiktok
2025-04-16T11:20:08.299588589Z 2025-04-16 11:20:08 DEBUG [root] v1 or v2 tiktok selector present
2025-04-16T11:20:08.299613797Z 2025-04-16 11:20:08 DEBUG [root] page is tiktok
2025-04-16T11:20:08.301420547Z 2025-04-16 11:20:08 DEBUG [root] No selector in list found: .captcha-disable-scroll img.captcha_verify_img_slide
2025-04-16T11:20:08.303509547Z 2025-04-16 11:20:08 DEBUG [root] No selector in list found: .captcha-verify-container #captcha-verify-image
2025-04-16T11:20:08.305588839Z 2025-04-16 11:20:08 DEBUG [root] No selector in list found: .captcha-disable-scroll [data-testid=whirl-inner-img]
2025-04-16T11:20:08.309702297Z 2025-04-16 11:20:08 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:20:08.309717172Z 2025-04-16 11:20:08 DEBUG [root] detected rotate v2
2025-04-16T11:20:08.309718797Z 2025-04-16 11:20:08 DEBUG [root] Detected rotate v2
2025-04-16T11:20:08.313432922Z 2025-04-16 11:20:08 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:20:08.315640630Z 2025-04-16 11:20:08 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:20:08.316135672Z 2025-04-16 11:20:08 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:20:08.898153339Z 2025-04-16 11:20:08 DEBUG [root] Got API response
2025-04-16T11:20:08.898644922Z 2025-04-16 11:20:08 DEBUG [root] Solution angle: angle=81
2025-04-16T11:20:08.906833464Z 2025-04-16 11:20:08 DEBUG [root] Solution distance: 63
2025-04-16T11:20:11.622864507Z 2025-04-16 11:20:11 DEBUG [root] page is tiktok
2025-04-16T11:20:16.662694926Z 2025-04-16 11:20:16 DEBUG [root] clicked refresh button
2025-04-16T11:20:19.675316469Z 2025-04-16 11:20:19 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:20:19.678432719Z 2025-04-16 11:20:19 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:20:19.679237094Z 2025-04-16 11:20:19 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:20:20.257146844Z 2025-04-16 11:20:20 DEBUG [root] Got API response
2025-04-16T11:20:20.257620678Z 2025-04-16 11:20:20 DEBUG [root] Solution angle: angle=81
2025-04-16T11:20:20.266634053Z 2025-04-16 11:20:20 DEBUG [root] Solution distance: 63
2025-04-16T11:20:22.954360179Z 2025-04-16 11:20:22 DEBUG [root] page is tiktok
2025-04-16T11:20:27.997668334Z 2025-04-16 11:20:27 DEBUG [root] clicked refresh button
2025-04-16T11:20:31.013241752Z 2025-04-16 11:20:31 DEBUG [root] Detected selector: .captcha-verify-container > div > div > div > img.cap-absolute from list .captcha-verify-container > div > div > div > img.cap-absolute
2025-04-16T11:20:31.017180502Z 2025-04-16 11:20:31 DEBUG [root] fetching blob:https://www.tiktok.com/10fa36b0-84f3-4f30-8932-2b49df4ee099 with async playwright javascript evaluate
2025-04-16T11:20:31.017752335Z 2025-04-16 11:20:31 DEBUG [root] fetching blob:https://www.tiktok.com/e627bf87-38ca-41c2-bd04-e368dc31473d with async playwright javascript evaluate
2025-04-16T11:20:31.595679502Z 2025-04-16 11:20:31 DEBUG [root] Got API response
2025-04-16T11:20:31.595921211Z 2025-04-16 11:20:31 DEBUG [root] Solution angle: angle=81
2025-04-16T11:20:31.605928127Z 2025-04-16 11:20:31 DEBUG [root] Solution distance: 63
2025-04-16T11:20:33.990607878Z 2025-04-16 11:20:33 DEBUG [root] page is tiktok
2025-04-16T11:20:39.029793047Z 2025-04-16 11:20:39 DEBUG [root] clicked refresh button
2025-04-16T11:20:42.039079966Z 2025-04-16 11:20:42 DEBUG [root] page is tiktok
2025-04-16T11:20:52.043781929Z 2025-04-16 11:20:52 DEBUG [root] page is tiktok
2025-04-16T11:20:52.047356345Z 2025-04-16 11:20:52 DEBUG [root] v1 or v2 tiktok selector present
```

**Comment by lavas1997** [comment]
I didn't test it for `PlaywrightSolver`, we don't have sync solution for TikTok at all

**Comment by lavas1997** [comment]
It's not obvious at all, but eventually what's helped to me is launching browser in `headless=True` mode to stop solving solution fetch same captcha URLs.

**Comment by gbiz123** [comment]
> It's not obvious at all, but eventually what's helped to me is launching browser in `headless=True` mode to stop solving solution fetch same captcha URLs.

Interesting. I have seen on headless=False that sometimes it grabs the same URL, but sometimes it doesn't. Will need to continue to look for patterns

**Comment by gbiz123** [comment]
> It's not obvious at all, but eventually what's helped to me is launching browser in `headless=True` mode to stop solving solution fetch same captcha URLs.

Okay, I have implemented a solution that should fix this issue and be extremely beneficial in other ways.  I added a function that simply loads the chrome extension when you launch the browser. Using this new function, rather than making a blocking call and needing to anticipate every time a captcha appears, it will be solved asynchronously whenever it appears automatically.

```py
import asyncio
from playwright.async_api import async_playwright
from temu_captcha_solver import make_async_playwright_solver_context

async def main():
    api_key = "YOUR_API_KEY_HERE"
    async with async_playwright() as p:
        context = await make_async_playwright_solver_context(p, api_key) # Returns playwright BrowserContext instance
        # ... [The rest of your code that accesses temu goes here]

asyncio.run(main())
```

Benefits of this approach:

- It does not have the issue we are discussing here
- You don't need to anticipate when captchas appear
- Your bot won't crash when there is an error in the captcha solver
- You don't need to block your script to wait for captchas to appear

This is available in version 8.0.0

**Comment by lavas1997** [comment]
That's great!
Can I ask you to make an option of creation persistent context with that extension?

**Comment by gbiz123** [comment]
> That's great! Can I ask you to make an option of creation persistent context with that extension?

Check the code implementation from the last commit, in the new file `launcher.py`. It creates a persistent context by default, and all of the **kwargs passed to the function are passed directly to `launch_persistent_context`
